#!/usr/bin/env sh
# Gradle wrapper script (Unix-based systems)
# Downloaded from gradle.org, or generated by Android Studio
# Make sure to set executable permission: chmod +x gradlew

export JAVA_HOME=${JAVA_HOME:-/usr/lib/jvm/java-17-openjdk-amd64}
DIR="$( cd "$( dirname "$0" )" && pwd )"
"$DIR"/gradle/wrapper/gradle-wrapper.jar "$@"